require "rails/generators"
require "rails/generators/migration"

module Maquina
  module Generators
    class RegistrationGenerator < Rails::Generators::Base
      include Rails::Generators::Migration

      source_root File.expand_path("templates", __dir__)

      class_option :skip_views, type: :boolean, default: false,
        desc: "Skip view templates"
      class_option :quiet, type: :boolean, default: false,
        desc: "Suppress post-install instructions"

      def self.next_migration_number(dirname)
        current = Time.now.utc.strftime("%Y%m%d%H%M%S")

        if @prev_migration_nr && @prev_migration_nr >= current
          current = @prev_migration_nr.succ
        end

        existing = Dir.glob("#{dirname}/[0-9]*_*.rb").map { |f| File.basename(f).split("_", 2).first }
        max_existing = existing.max

        if max_existing && max_existing >= current
          current = max_existing.succ
        end

        @prev_migration_nr = current
      end

      # 1. Run Rails authentication generator
      def run_rails_authentication
        return unless rails_app?

        generate "authentication"
      end

      # 2. Account model
      def create_account_model
        template "app/models/account.rb.tt", "app/models/account.rb"
      end

      # 3. Update User model (replace Rails-generated)
      def update_user_model
        template "app/models/user.rb.tt", "app/models/user.rb"
      end

      # 4. Update Current model (replace Rails-generated)
      def update_current_model
        template "app/models/current.rb.tt", "app/models/current.rb"
      end

      # 5. Registration controller
      def create_registration_controller
        template "app/controllers/registrations_controller.rb.tt",
          "app/controllers/registrations_controller.rb"
      end

      # 6. Views
      def create_views
        return if options[:skip_views]

        template "app/views/registrations/new.html.erb.tt",
          "app/views/registrations/new.html.erb"
        template "app/views/sessions/new.html.erb.tt",
          "app/views/sessions/new.html.erb"
      end

      # 7. Locale files
      def create_locale_files
        copy_file "config/locales/registration.en.yml", "config/locales/registration.en.yml"
        copy_file "config/locales/registration.es.yml", "config/locales/registration.es.yml"
      end

      # 8. Routes
      def add_routes
        route_content = <<~RUBY
          # Registration routes (generated by maquina:registration)
          resources :registrations, only: [:new, :create]
        RUBY

        route route_content
      end

      # 9. Enable bcrypt
      def enable_bcrypt
        gemfile_path = File.join(destination_root, "Gemfile")
        if File.exist?(gemfile_path)
          content = File.read(gemfile_path)
          if content.include?('# gem "bcrypt"')
            gsub_file "Gemfile", '# gem "bcrypt"', 'gem "bcrypt"'
          elsif !content.include?('gem "bcrypt"')
            append_to_file "Gemfile", "\ngem \"bcrypt\"\n"
          end
        end
      end

      # 10. Migrations
      def add_migrations
        migration_template "migration_create_accounts.rb.tt",
          "db/migrate/create_accounts.rb"
        migration_template "migration_add_account_fields_to_users.rb.tt",
          "db/migrate/add_account_fields_to_users.rb"
      end

      # 11. Post-install message
      def show_post_install
        return if options[:quiet]

        say ""
        say "Registration has been installed!", :green
        say ""
        say "Next steps:", :yellow
        say "  1. rails db:migrate                  # Run migrations"
        say "  2. rails server                      # Start the app"
        say "  3. Visit /registrations/new           # Sign-up page"
        say "  4. Visit /session/new                # Sign-in page"
        say ""
        say "Customization:", :yellow
        say "  - Edit app/models/account.rb to add account fields"
        say "  - Edit app/models/user.rb to customize roles or add fields"
        say "  - Edit config/locales/registration.*.yml to customize messages"
        say "  - Edit views to match your design"
        say ""
      end

      private

      def migration_version
        "[#{Rails::VERSION::MAJOR}.#{Rails::VERSION::MINOR}]"
      end

      def rails_app?
        File.exist?(File.join(destination_root, "bin/rails"))
      end
    end
  end
end
