require "rails/generators"
require "rails/generators/migration"

module Maquina
  module Generators
    class ClaveGenerator < Rails::Generators::Base
      include Rails::Generators::Migration

      source_root File.expand_path("templates", __dir__)

      class_option :skip_views, type: :boolean, default: false,
        desc: "Skip view templates"
      class_option :skip_registration, type: :boolean, default: false,
        desc: "Skip sign-up flow"

      def self.next_migration_number(dirname)
        sleep(1) if @prev_migration_nr == Time.now.utc.strftime("%Y%m%d%H%M%S")
        @prev_migration_nr = Time.now.utc.strftime("%Y%m%d%H%M%S")
      end

      # 1. Models
      def create_models
        template "app/models/current.rb.tt", "app/models/current.rb"
        template "app/models/session.rb.tt", "app/models/session.rb"
        template "app/models/email_verification.rb.tt", "app/models/email_verification.rb"
        template "app/models/user.rb.tt", "app/models/user.rb"
      end

      # 2. Controllers
      def create_controllers
        template "app/controllers/concerns/authentication.rb.tt",
          "app/controllers/concerns/authentication.rb"
        template "app/controllers/sessions_controller.rb.tt",
          "app/controllers/sessions_controller.rb"
        template "app/controllers/session/verifications_controller.rb.tt",
          "app/controllers/session/verifications_controller.rb"
        template "app/controllers/session/verification_resends_controller.rb.tt",
          "app/controllers/session/verification_resends_controller.rb"

        unless options[:skip_registration]
          template "app/controllers/registrations_controller.rb.tt",
            "app/controllers/registrations_controller.rb"
          template "app/controllers/registration/verifications_controller.rb.tt",
            "app/controllers/registration/verifications_controller.rb"
          template "app/controllers/registration/verification_resends_controller.rb.tt",
            "app/controllers/registration/verification_resends_controller.rb"
        end
      end

      # 3. Mailer
      def create_mailer
        template "app/mailers/verification_mailer.rb.tt",
          "app/mailers/verification_mailer.rb"
      end

      # 4. Helper
      def create_helper
        template "app/helpers/authentication_helper.rb.tt",
          "app/helpers/authentication_helper.rb"
      end

      # 5. Job
      def create_job
        template "app/jobs/authentication_cleanup_job.rb.tt",
          "app/jobs/authentication_cleanup_job.rb"
      end

      # 6. Views
      def create_views
        return if options[:skip_views]

        template "app/views/sessions/new.html.erb.tt",
          "app/views/sessions/new.html.erb"
        template "app/views/session/verifications/new.html.erb.tt",
          "app/views/session/verifications/new.html.erb"

        unless options[:skip_registration]
          template "app/views/registrations/new.html.erb.tt",
            "app/views/registrations/new.html.erb"
          template "app/views/registration/verifications/new.html.erb.tt",
            "app/views/registration/verifications/new.html.erb"
        end

        template "app/views/verification_mailer/verification_code.html.erb.tt",
          "app/views/verification_mailer/verification_code.html.erb"
        template "app/views/verification_mailer/verification_code.text.erb.tt",
          "app/views/verification_mailer/verification_code.text.erb"
      end

      # 7. Locale files
      def create_locale_files
        copy_file "config/locales/clave.en.yml", "config/locales/clave.en.yml"
        copy_file "config/locales/clave.es.yml", "config/locales/clave.es.yml"
      end

      # 9. Test helper
      def create_test_helper
        template "test/test_helpers/session_test_helper.rb.tt",
          "test/test_helpers/session_test_helper.rb"
      end

      # 10. Include Authentication in ApplicationController
      def configure_application_controller
        sentinel = "class ApplicationController < ActionController::Base\n"
        inject_into_file "app/controllers/application_controller.rb",
          "  include Authentication\n",
          after: sentinel
      end

      # 11. Routes
      def add_routes
        route_content = <<~RUBY
          # Authentication routes (generated by maquina:clave)
          resource :session, only: [:new, :create, :destroy] do
            resource :verification, only: [:new, :create], controller: "session/verifications"
            resource :verification_resend, only: [:create], controller: "session/verification_resends"
          end
        RUBY

        unless options[:skip_registration]
          route_content += <<~RUBY

            resource :registration, only: [:new, :create] do
              resource :verification, only: [:new, :create], controller: "registration/verifications"
              resource :verification_resend, only: [:create], controller: "registration/verification_resends"
            end
          RUBY
        end

        route route_content
      end

      # 12. Enable bcrypt
      def enable_bcrypt
        gemfile_path = File.join(destination_root, "Gemfile")
        if File.exist?(gemfile_path)
          content = File.read(gemfile_path)
          if content.include?('# gem "bcrypt"')
            gsub_file "Gemfile", '# gem "bcrypt"', 'gem "bcrypt"'
          elsif !content.include?('gem "bcrypt"')
            append_to_file "Gemfile", "\ngem \"bcrypt\"\n"
          end
        end
      end

      # 13. Migrations
      def add_migrations
        migration_template "migration_create_users.rb.tt",
          "db/migrate/create_users.rb"
        migration_template "migration_create_sessions.rb.tt",
          "db/migrate/create_sessions.rb"
        migration_template "migration_create_email_verifications.rb.tt",
          "db/migrate/create_email_verifications.rb"
      end

      # 14. Post-install message
      def show_post_install
        say ""
        say "Clave authentication has been installed!", :green
        say ""
        say "Next steps:", :yellow
        say "  1. bundle install                    # Install bcrypt"
        say "  2. rails db:migrate                  # Run migrations"
        say "  3. rails server                      # Start the app"
        say "  4. Visit /session/new                # Sign-in page"
        unless options[:skip_registration]
          say "  5. Visit /registration/new           # Sign-up page"
        end
        say ""
        say "Optional:", :yellow
        say "  - Edit app/controllers/concerns/authentication.rb to customize redirect URLs"
        say "  - Edit config/locales/clave.*.yml to customize messages"
        say "  - Set up Action Mailer for email delivery (letter_opener for development)"
        say ""
      end

      private

      def migration_version
        "[#{Rails::VERSION::MAJOR}.#{Rails::VERSION::MINOR}]"
      end
    end
  end
end
